name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

jobs:
  test:
    name: test application
    runs-on: ubuntu-latest
    
    steps:
    - name: test application
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install virtualenv
    - run: virtualenv venv
    - run: source venv/bin/activate
    - run: pip install -r requirements.txt
    - run: python -m pytest .
    
  build-and-push-to-docker:
    name: build and push to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
#       - name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           push: true
#           tags: ykbhlvck/husqvarna_isdoc:latest
  
#   deploy:
#     name: deploy on VM
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
      
#     steps:
#     - name: Executing remote ssh docker deploy
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.DEPLOY_IP }}
#         username: ${{ secrets.DEPLOY_USERNAME }}
#         password: ${{ secrets.DEPLOY_PASSWORD }}
#         script: |
#           cd ${{ secrets.PROJECT_PATH }}
#           docker-compose pull && docker-compose up --detach && docker system prune -f
      
  
